"""add wind_speed column

Revision ID: 2c5b70b0d0fd
Revises: e04332675a67
Create Date: 2025-08-18 19:56:37.360854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c5b70b0d0fd'
down_revision = 'e04332675a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wind_speed', sa.Float(), nullable=False, comment='风速(m/s)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_data', schema=None) as batch_op:
        batch_op.drop_column('wind_speed')

    # ### end Alembic commands ###
