"""Initial tables

Revision ID: e04332675a67
Revises: 
Create Date: 2025-08-18 19:31:36.345112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e04332675a67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False, comment='城市名称'),
    sa.Column('temperature', sa.Float(), nullable=False, comment='温度(℃)'),
    sa.Column('humidity', sa.Float(), nullable=False, comment='湿度(%)'),
    sa.Column('timestamp', sa.DateTime(), nullable=True, comment='记录时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weather_data', schema=None) as batch_op:
        batch_op.create_index('idx_city_time', ['city', 'timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_data', schema=None) as batch_op:
        batch_op.drop_index('idx_city_time')

    op.drop_table('weather_data')
    # ### end Alembic commands ###
